Models/ThemeModel.cs
namespace Themeabay.Nop.Plugin.Switcha.Models
{
    public sealed class ThemeModel
    {
        public string FriendlyName { get; set; }

        public string SystemName { get; set; }

        public string PreviewImageUrl { get; set; }

        public bool IsSelected { get; set; }
    }
}

Components/NopThemesViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain;
using Nop.Services.Security;
using Nop.Services.Themes;
using Nop.Web.Framework.Components;
using Nop.Web.Framework.Themes;
using Themeabay.Nop.Plugin.Switcha.Models;

namespace Themeabay.Nop.Plugin.Switcha.Components
{
    [ViewComponent(Name = "WidgetsNopThemesSelector")]
    public class NopThemesSelectorViewComponent : NopViewComponent
    {
        private readonly IPermissionService _permissionService;
        private readonly IThemeProvider _themeProvider;
        private readonly IThemeContext _themeContext;
        private readonly StoreInformationSettings _storeInformationSettings;

        public NopThemesSelectorViewComponent(IThemeContext themeContext,
            IThemeProvider themeProvider,
            IPermissionService permissionService,
            StoreInformationSettings storeInformationSettings)
        {
            _themeProvider = themeProvider;
            _themeContext = themeContext;
            _storeInformationSettings = storeInformationSettings;
            _permissionService = permissionService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string widgetZone, object additionalData)
        {
            // only admin user can see this button.
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.AccessAdminPanel))
            {
                return Content(string.Empty);
            }

            var workingThemeName = await _themeContext.GetWorkingThemeNameAsync();
            if (string.IsNullOrEmpty(workingThemeName))
            {
                workingThemeName = _storeInformationSettings.DefaultStoreTheme;
            }
            var model = (await _themeProvider.GetThemesAsync()).Select(k => new ThemeModel()
            {
                FriendlyName = k.FriendlyName,
                SystemName = k.SystemName,
                PreviewImageUrl = k.PreviewImageUrl,
                IsSelected = k.SystemName == workingThemeName
            }).ToList();
            // no any theme is matched
            if (!model.Any(k => k.IsSelected))
            {
                var theme = model.Where(k => k.SystemName == _storeInformationSettings.DefaultStoreTheme).First();
                theme.IsSelected = true;
            }
            return View("~/Plugins/Themeabay.Switcha/Views/NopThemesSelector.cshtml", model);
        }
    }
}

Controllers/SwitchaController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Nop.Core.Domain;
using Nop.Services.Themes;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Themeabay.Nop.Plugin.Switcha.Controllers
{
    public class SwitchaController : BasePluginController
    {

        [AuthorizeAdmin]
        public IActionResult Preview(string theme, string returnUrl = null)
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                returnUrl = "/";
            }
            Uri.TryCreate(new Uri(Request.GetDisplayUrl()), returnUrl, out Uri uri);
            var queryParams = QueryHelpers.ParseQuery(uri.Query);
            queryParams["theme_preview"] = theme;
            var queryStrings = string.Join("&", queryParams.Select(k => k.Key + "=" + k.Value.First()));
            returnUrl = uri.AbsolutePath;
            if (!string.IsNullOrEmpty(queryStrings))
            {
                returnUrl += "?" + queryStrings;
            }
            return Redirect(returnUrl);
        }
    }
}

Views/NopThemesSelector.cshtml
@using Nop.Web.Framework.UI
@model IList<Themeabay.Nop.Plugin.Switcha.Models.ThemeModel>
@inject Nop.Core.IWebHelper WebHelper
#if (NET6_0)
    @inject INopHtmlHelper NopHtml
#else
    @inject IHtmlHelper NopHtml

@{
    var workingTheme = Model.Where(k => k.IsSelected).First();
    var returnUrl = WebHelper.GetRawUrl(Context.Request);
    NopHtml.AppendCssFileParts("~/Plugins/Themeabay.Switcha/Content/styles.css", excludeFromBundle: true);
}

<div class="theme-switcha">
    <div class="theme-switcha__selector">
        <span class="theme-switcha__theme">@(workingTheme.FriendlyName)</span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
        </svg>
        <div class="theme-switcha__themes">
            @foreach (var theme in Model)
            {
                <div class="theme-switcha-card @(theme.IsSelected?"active":null)">
                    <a asp-controller="Switcha" asp-action="Preview" asp-route-theme="@theme.SystemName" asp-route-returnUrl="@returnUrl">
                        <div class="theme-switcha-card__image">
                            <img src="@Url.Content(theme.PreviewImageUrl)" />
                        </div>
                        <div class="theme-switcha-card__title">
                            @theme.FriendlyName <svg class="icon-check-svg" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M13.485 1.431a1.473 1.473 0 0 1 2.104 2.062l-7.84 9.801a1.473 1.473 0 0 1-2.12.04L.431 8.138a1.473 1.473 0 0 1 2.084-2.083l4.111 4.112 6.82-8.69a.486.486 0 0 1 .04-.045z"></path></svg>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>